### ISSUE TITLE
UI Data-Visualization Discrepancy - Identify VS Valve Details: #WGG24_013463V

### ISSUE THREAD

**Issue by slmessier** [JMurk/Valve_Hydrant_Mobile_Issues#85]
Users (Alan F) has reported a valve shows as a hydrant lead valve in the identify results, but shows as a division valve in the valve details.

see WGG24__013463V
@ 333 W Ostend

The issue may potentially have to do with fact that this valve was added from WA_Valve without a pre-existing status record ... perhaps the details were inadvertently set as a default type of "division valve"???

**Comment by taojun545** [comment]
The valve details was showing wrong "Use". I checked the data, and that valve is "Combined Fire and Domestic Service Valve". But the "Use" drop-down field in the details form only take number value, otherwise it will show the first default option "division valve".

I will change the field in the form, and it will show correct value.

**Comment by taojun545** [comment]
I updated the valve details form on DEV, and it shows correct values of the valve now.

**Comment by rssidlowski** [comment]
Verified in dev. Please promote this change to production.

**Comment by taojun545** [comment]
Updated on PROD.

**Comment by rssidlowski** [comment]
Verified in PROD.
