### ISSUE TITLE
Valves & Hydrants - Valve History not updating correctly

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Valve_Hydrant_Mobile_Issues#86]
Valve histories are not associating properly / displaying properly.

For instance, see valve WEE25__019411V

I updated this, but the history shows my edits split between the last two histories.  History with edit date of today is from previous record.  History of previous record is from today's edits.

**Comment by taojun545** [comment]
@alanfoster99, I fixed the valve WEE25__019411V, and it shows correct history now.

When user updates the VALVE_STATUS, database will auto-insert one record (08/10/2016) into VALVE_STATUS_HISTORY, then the code will find that new history record (08/10/2016) and update it.
But the bug is the code found wrong history record (12/02/2015).

I have update the code on both DEV and PROD.

**Comment by alanfoster99** [comment]
Confirmed and closing
